name: Latest book list from a goodreads
on:
  schedule: # Run workflow automatically
    # This will make it run every 5 days
    - cron: "0 0 */5 * *"
    # Run workflow manually (without waiting for the cron to be called), through the Github Actions Workflow page directly
  workflow_dispatch:

jobs:
  update-readme-with-goodreads-books:
    name: Update this repo's README with what you're currently reading
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
      - uses: zwacky/goodreads-profile-workflow@v1.1.2
        with:
          # Replace this with your goodreads user id (go to "My Books" on goodreads to see it in the URL)
          goodreads_user_id: "5243820"
          shelf: "currently-reading"
  update-readme-with-goodreads-books-read:
    name: Update this repo's README with the last 5 books you've read
    needs: update-readme-with-goodreads-books
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          clean: true
      - run: |
          git reset --hard origin/main
      - uses: zwacky/goodreads-profile-workflow@v1.1.2
        with:
          # Replace this with your goodreads user id (go to "My Books" on goodreads to see it in the URL)
          goodreads_user_id: "5243820"
          shelf: "read"
          comment_tag_name: "GOODREADS-READ-LIST"
          max_books_count: "5"
          template: "- [$title]($url) by $author ($my_rating_stars)"
